device: ''

#deepsort
config_deepsort: ../../settings/deep_sort.yaml
deep_sort_weights: ../../models/ckpt.t7

#yolo
yolo_weights: ../../models/yolov5s.pt
agnostic_nms: false
augment: false
classes: [7]
conf_thres: 0.35
imgsz:
- 640
iou_thres: 0.5
max_det: 1000
dnn: false
evaluate: false
half: false
visualize: false

#in-out
fourcc: mp4v
source: ../../videos/sample2.mp4
output: inference/output
save_csv: true
save_txt: true
save_vid: true
show_vid: false

#lines zones
upper_ratio: 0.2
right_ratio: 0.5

#DB
upload_db: false
